I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1202, in script
    call screen puzzle_drag_2
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "game/Quiz.rpy", line 124, in execute
    screen puzzle_drag_2():
  File "game/Quiz.rpy", line 124, in execute
    screen puzzle_drag_2():
  File "game/Quiz.rpy", line 129, in execute
    draggroup:
  File "game/Quiz.rpy", line 130, in execute
    drag:
  File "game/Quiz.rpy", line 130, in keywords
    drag:
  File "game/Quiz.rpy", line 131, in <module>
    xpos pos1[0]
NameError: name 'pos1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1202, in script
    call screen puzzle_drag_2
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 1974, in execute
    self.call("execute")
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ast.py", line 1953, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\statements.py", line 374, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 671, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\exports\statementexports.py", line 345, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\core.py", line 2188, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\core.py", line 2705, in interact_core
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\displayable.py", line 434, in visit_all
    d.visit_all(callback, seen)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 480, in visit_all
    callback(self)
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\core.py", line 2705, in <lambda>
    root_widget.visit_all(lambda d : d.per_interact())
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 491, in per_interact
    self.update()
  File "D:\RenPy\renpy-8.3.0-sdk\renpy\display\screen.py", line 697, in update
    self.screen.function(**self.scope)
  File "game/Quiz.rpy", line 124, in execute
    screen puzzle_drag_2():
  File "game/Quiz.rpy", line 124, in execute
    screen puzzle_drag_2():
  File "game/Quiz.rpy", line 129, in execute
    draggroup:
  File "game/Quiz.rpy", line 130, in execute
    drag:
  File "game/Quiz.rpy", line 130, in keywords
    drag:
  File "game/Quiz.rpy", line 131, in <module>
    xpos pos1[0]
NameError: name 'pos1' is not defined

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.0.24082114
 
Tue Dec 10 08:26:56 2024
