I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1821, in script
    with moveoutleft
  File "game/script.rpy", line 1821, in <module>
    with moveoutleft
NameError: name 'moveout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1821, in script
    with moveoutleft
  File "D:\engine_renpy\renpy-8.3.2-sdk\renpy\ast.py", line 1354, in execute
    trans = renpy.python.py_eval(self.expr)
  File "D:\engine_renpy\renpy-8.3.2-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\engine_renpy\renpy-8.3.2-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1821, in <module>
    with moveoutleft
NameError: name 'moveout' is not defined

Windows-10-10.0.22631 AMD64
Ren'Py 8.3.3.24111502
 
Mon Dec  9 19:22:17 2024
